### ISSUE TITLE
Заповедники

### ISSUE THREAD

**Issue by AlexDereka** [liosha/osm2mp-garmin-open#2]
интересует 
boundary=protected_area
protect_class = 3 и 4 и 5
возможно настроить ?

на текущий момент настроено только
        - leisure = nature_reserve
        - boundary = national_park

**Comment by liosha** [comment]
Можно. А почему только 3 и 4 и 5?

**Comment by AlexDereka** [comment]
можно думаю от 1 до 5 так как часто используется. 
С 6 идут  отличия по регионам. добавить ещё можно 7.
Отображение на карте можно использовать как тут
http://www.transparentworld.ru/ru/environment/oopt/oopt-map/
но нужно смотреть чтобы не пересекалось с типом 25 

используется также в России 14 и 24, но нужно думать про отображение. 14 и 24 это уже лучьше индивидуально самому настраивать.

**Comment by liosha** [comment]
Добавил
